version: "3"

services:
  tgbot:
    image: user-group-project
    expose:
      - "5000"
    ports:
      - "5000:5000"
    restart: on-failure
    environment:
      TOKEN_BOT: ${BOT_TOKEN}

    depends_on:
      - db
    volumes:
      - ".:/opt/app"

    command: python manage.py runbot
    build:
      context: .
      dockerfile: Dockerfile

  app:
    image: user-group-project
    ports:
      - "8001:8000"
    volumes:
      - ".:/opt/app"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5434:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: .
      dockerfile: Dockerfile